baseURL = ""
languageCode = "en-us"
theme = "SimpleIntro"
publishDir = "public"

[params]
    mainbg = "images/screenshot.png"
    mainTitle = "ISTC 2023"
    mainText = "International Symposium on Topics in Coding in Brest"

